apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "goserver-infnet"
  labels:
    app: "goserver-infnet"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: "goserver-infnet"
  template:
    metadata:
      labels:
        app: "goserver-infnet"
    spec:
      containers:
      - name: "goserver-infnet"
        image: "oandremotta/projeto-infnet"