apiVersion: v1
kind: Service
metadata:
  name: "goserver-infnet-service"
spec:
  selector:
    app: "goserver-infnet"
  type: NodePort
  ports:
  - name: goserver-infnet-service
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30001 #30.000 ~32.767
    