apiVersion: v1
kind: Service
metadata:
  name: "goserver-infnet-service"
spec:
  selector:
    app: "goserver-infnet"
  type: ClusterIP
  ports:
    - name: "http"         
      port: 80             
      targetPort: 80       
      protocol: TCP
