apiVersion: v1
kind: Service
metadata:
  name: "goserver-infnet-service"
spec:
  selector:
    app: "goserver-infnet"
  type: ClusterIP
  ports:
    - name: goserver-infnet-service
    - port: 80
      protocol: TCP
    