name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Minikube and kubectl
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.25.2/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          curl -LO https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Set kubectl context to Minikube
        run: |
          kubectl config use-context minikube

      - name: Install Helm
        run: |
          curl https://get.helm.sh/helm-v3.9.0-linux-amd64.tar.gz -o helm.tar.gz
          tar -zxvf helm.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-release ./helm-chart -f ./helm/values.yaml --namespace default
